//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.06 at 05:22:07 PM EST 
//


package model.outcomes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model.outcomes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model.outcomes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LearningOutcomes }
     * 
     */
    public LearningOutcomes createLearningoutcomes() {
        return new LearningOutcomes();
    }

    /**
     * Create an instance of {@link LearningOutcomes.Outcomes }
     * 
     */
    public LearningOutcomes.Outcomes createLearningoutcomesOutcomes() {
        return new LearningOutcomes.Outcomes();
    }

}
