//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.06 at 05:21:13 PM EST 
//


package model.mappings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XMLMappingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XMLMappingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unitcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="teachingperiod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="outcomecollections">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLMappingType", propOrder = {
    "unitcode",
    "teachingperiod",
    "outcomecollections"
})
public class XMLMappingType {

    @XmlElement(required = true)
    protected String unitcode;
    @XmlElement(required = true)
    protected String teachingperiod;
    @XmlElement(required = true)
    protected XMLMappingType.Outcomecollections outcomecollections;

    /**
     * Gets the value of the unitcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitcode() {
        return unitcode;
    }

    /**
     * Sets the value of the unitcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitcode(String value) {
        this.unitcode = value;
    }

    /**
     * Gets the value of the teachingperiod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeachingperiod() {
        return teachingperiod;
    }

    /**
     * Sets the value of the teachingperiod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeachingperiod(String value) {
        this.teachingperiod = value;
    }

    /**
     * Gets the value of the outcomecollections property.
     * 
     * @return
     *     possible object is
     *     {@link XMLMappingType.Outcomecollections }
     *     
     */
    public XMLMappingType.Outcomecollections getOutcomecollections() {
        return outcomecollections;
    }

    /**
     * Sets the value of the outcomecollections property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLMappingType.Outcomecollections }
     *     
     */
    public void setOutcomecollections(XMLMappingType.Outcomecollections value) {
        this.outcomecollections = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "guid"
    })
    public static class Outcomecollections {

        protected List<String> guid;

        /**
         * Gets the value of the guid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the guid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGuid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getGuid() {
            if (guid == null) {
                guid = new ArrayList<String>();
            }
            return this.guid;
        }

    }

}
