//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.30 at 08:09:15 PM EST 
//


package edu.monash.madam.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import edu.monash.madam.model.Checkbox;
import edu.monash.madam.model.SubtaskTypeException;


/**
 * <p>Java class for CheckboxType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CheckboxType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.monash.edu/MADAM}Mark">
 *       &lt;attribute name="maxMark" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CheckboxType")
public class CheckboxType
    extends Mark
{

    @XmlAttribute(name = "maxMark")
    protected BigDecimal maxMark;

    /**
     * Gets the value of the maxMark property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxMark() {
        return maxMark;
    }

    /**
     * Sets the value of the maxMark property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxMark(BigDecimal value) {
        this.maxMark = value;
    }
    
    @XmlAttribute(name = "bonus")
    protected Boolean bonus;
    
    public Boolean getBonus() {
    	return bonus;
    }
    
    public void setBonus(Boolean value) {
    	this.bonus = value;
    }

	@Override
	public edu.monash.madam.model.Mark toMark() throws SubtaskTypeException {
    	Checkbox cb = new Checkbox();
    	cb.setBonus(bonus.asBoolean());
    	cb.setDescription(description);
    	cb.setGroup(group.asBoolean());
    	cb.setLabel(label);
    	cb.setMarkerInstruction(markerInstruction);
    	cb.setMaxMark(maxMark.floatValue());
    	cb.setName(name);
    	
    	return cb;
	}

}
