//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.30 at 08:09:15 PM EST 
//


package edu.monash.madam.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.monash.madam package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.monash.madam
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Scheme }
     * 
     */
    public Scheme createScheme() {
        return new Scheme();
    }

    /**
     * Create an instance of {@link NumericType }
     * 
     */
    public NumericType createNumericType() {
        return new NumericType();
    }

    /**
     * Create an instance of {@link QualitativeType }
     * 
     */
    public QualitativeType createQualitativeType() {
        return new QualitativeType();
    }

    /**
     * Create an instance of {@link Scheme.Tasks }
     * 
     */
    public Scheme.Tasks createSchemeTasks() {
        return new Scheme.Tasks();
    }

    /**
     * Create an instance of {@link CheckboxType }
     * 
     */
    public CheckboxType createCheckboxType() {
        return new CheckboxType();
    }

    /**
     * Create an instance of {@link CriteriaType }
     * 
     */
    public CriteriaType createCriteriaType() {
        return new CriteriaType();
    }

    /**
     * Create an instance of {@link ScaleType }
     * 
     */
    public ScaleType createScaleType() {
        return new ScaleType();
    }

    /**
     * Create an instance of {@link CriterionType }
     * 
     */
    public CriterionType createCriterionType() {
        return new CriterionType();
    }

    /**
     * Create an instance of {@link NumericType.Subtasks }
     * 
     */
    public NumericType.Subtasks createNumericTypeSubtasks() {
        return new NumericType.Subtasks();
    }

    /**
     * Create an instance of {@link QualitativeType.Subtasks }
     * 
     */
    public QualitativeType.Subtasks createQualitativeTypeSubtasks() {
        return new QualitativeType.Subtasks();
    }

}
