//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.30 at 08:09:15 PM EST 
//


package edu.monash.madam.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import edu.monash.madam.model.Criterion;
import edu.monash.madam.model.QTask;
import edu.monash.madam.model.SubtaskTypeException;


/**
 * <p>Java class for QualitativeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QualitativeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.monash.edu/MADAM}Mark">
 *       &lt;sequence>
 *         &lt;element name="Subtasks" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="QTask" type="{http://www.monash.edu/MADAM}QualitativeType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Criteria" type="{http://www.monash.edu/MADAM}CriteriaType" minOccurs="0"/>
 *         &lt;element name="Scale" type="{http://www.monash.edu/MADAM}ScaleType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="hasComment" type="{http://www.monash.edu/MADAM}Boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QualitativeType", propOrder = {
    "subtasks",
    "criteria",
    "scale"
})
public class QualitativeType
    extends Mark
{

    @XmlElement(name = "Subtasks")
    protected QualitativeType.Subtasks subtasks;
    @XmlElement(name = "Criteria")
    protected CriteriaType criteria;
    @XmlElement(name = "Scale")
    protected ScaleType scale;
    @XmlAttribute(name = "hasComment")
    protected Boolean hasComment;

    /**
     * Gets the value of the subtasks property.
     * 
     * @return
     *     possible object is
     *     {@link QualitativeType.Subtasks }
     *     
     */
    public QualitativeType.Subtasks getSubtasks() {
        return subtasks;
    }

    /**
     * Sets the value of the subtasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualitativeType.Subtasks }
     *     
     */
    public void setSubtasks(QualitativeType.Subtasks value) {
        this.subtasks = value;
    }

    /**
     * Gets the value of the criteria property.
     * 
     * @return
     *     possible object is
     *     {@link CriteriaType }
     *     
     */
    public CriteriaType getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriteriaType }
     *     
     */
    public void setCriteria(CriteriaType value) {
        this.criteria = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link ScaleType }
     *     
     */
    public ScaleType getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScaleType }
     *     
     */
    public void setScale(ScaleType value) {
        this.scale = value;
    }

    /**
     * Gets the value of the hasComment property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getHasComment() {
        return hasComment;
    }

    /**
     * Sets the value of the hasComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasComment(Boolean value) {
        this.hasComment = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="QTask" type="{http://www.monash.edu/MADAM}QualitativeType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "qTask"
    })
    public static class Subtasks {

        @XmlElement(name = "QTask")
        protected List<QualitativeType> qTask;

        /**
         * Gets the value of the qTask property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the qTask property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQTask().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link QualitativeType }
         * 
         * 
         */
        public List<QualitativeType> getQTask() {
            if (qTask == null) {
                qTask = new ArrayList<QualitativeType>();
            }
            return this.qTask;
        }

    }


	@Override
	public edu.monash.madam.model.Mark toMark() throws SubtaskTypeException {
		QTask qt = new QTask();
    	qt.setDescription(description);
    	qt.setGroup(group.asBoolean());
    	qt.setHasComment(hasComment.asBoolean());
    	qt.setLabel(label);
    	qt.setMarkerInstruction(markerInstruction);
    	qt.setName(name);
    	
    	// sort out subtasks
    	for (Mark m: subtasks.getQTask()) {
    		qt.addSubtask(m.toMark());
    	}
    	
    	// sort out criteria
    	for (CriterionType ct: getCriteria().criterion) {
    		Criterion c = new Criterion(ct.getDescription(), ct.getScale().toScale());
    		c.setMarkerInstruction(ct.getMarkerInstruction());   		
    		qt.addCriterion(c);
    	}

		return qt;
	}

}
